"""Round-4 backend tests: Route Master via/excursion/day_title, lookup scoring,
occupancy extras costing, share price_breakdown sum, stays grouping."""
import pytest
import requests

from conftest import API


# ---------------- Route lookup combos ----------------
class TestRouteLookup:
    def test_lookup_via_combo(self, admin):
        r = admin.get(f"{API}/routes/lookup", params={"from_place": "Gangtok", "to_place": "Pelling", "via": "Ravangla"}, timeout=30)
        assert r.status_code == 200, r.text
        d = r.json()
        assert d["found"] is True
        assert d["day_title"] == "Transfer to Pelling via Ravangla Sightseeing"
        assert "Buddha Park" in d["description"]
        assert d["image_url"].startswith("http")

    def test_lookup_excursion_combo(self, admin):
        r = admin.get(f"{API}/routes/lookup", params={"from_place": "Gangtok", "excursion": "Tsomgo Lake & Baba Mandir"}, timeout=30)
        assert r.status_code == 200, r.text
        d = r.json()
        assert d["found"] is True
        assert d["day_title"] == "Full Day Excursion to Tsomgo Lake & Baba Mandir"
        assert "Tsomgo" in d["description"]

    def test_lookup_unknown_combo_auto_title(self, admin):
        r = admin.get(f"{API}/routes/lookup", params={"from_place": "Xtown", "to_place": "Ytown", "via": "Zstop"}, timeout=30)
        assert r.status_code == 200, r.text
        d = r.json()
        assert d["found"] is False
        assert d["day_title"] == "Transfer to Ytown via Zstop Sightseeing"
        assert d["description"] == ""

    def test_lookup_missing_params_400(self, admin):
        assert admin.get(f"{API}/routes/lookup", params={"from_place": "Gangtok"}, timeout=30).status_code == 400
        assert admin.get(f"{API}/routes/lookup", timeout=30).status_code == 400

    def test_lookup_unauthenticated_401(self):
        r = requests.get(f"{API}/routes/lookup", params={"from_place": "Gangtok", "to_place": "Pelling"}, timeout=30)
        assert r.status_code == 401

    def test_lookup_plain_transfer_no_via(self, admin):
        r = admin.get(f"{API}/routes/lookup", params={"from_place": "IXB/NJP", "to_place": "Gangtok"}, timeout=30)
        assert r.status_code == 200
        d = r.json()
        assert d["found"] is True
        assert d["day_title"] == "Transfer to Gangtok"


# ---------------- Route CRUD with new fields ----------------
class TestRouteCRUDNewFields:
    def test_route_roundtrip(self, admin):
        payload = {
            "from_place": "TEST_A", "to_place": "TEST_B", "via": "TEST_V",
            "excursion": "", "day_title": "TEST_ Custom Day Title",
            "description": "<p>TEST_ desc</p>", "image_url": "https://example.com/x.jpg",
        }
        r = admin.post(f"{API}/routes", json=payload, timeout=30)
        assert r.status_code == 200, r.text
        created = r.json()
        rid = created["id"]
        try:
            for k, v in payload.items():
                assert created[k] == v, k
            # GET list contains it
            lst = admin.get(f"{API}/routes", timeout=30).json()
            row = next((x for x in lst if x["id"] == rid), None)
            assert row is not None
            assert row["via"] == "TEST_V" and row["day_title"] == "TEST_ Custom Day Title"
            assert "_id" not in row
            # lookup returns the custom day_title (not autogenerated)
            lk = admin.get(f"{API}/routes/lookup", params={"from_place": "TEST_A", "to_place": "TEST_B", "via": "TEST_V"}, timeout=30).json()
            assert lk["found"] is True and lk["day_title"] == "TEST_ Custom Day Title"
            # PATCH
            p = admin.patch(f"{API}/routes/{rid}", json={"via": "TEST_V2", "excursion": "TEST_EX", "day_title": "TEST_ Updated"}, timeout=30)
            assert p.status_code == 200, p.text
            assert p.json()["via"] == "TEST_V2"
            row = next(x for x in admin.get(f"{API}/routes", timeout=30).json() if x["id"] == rid)
            assert row["excursion"] == "TEST_EX" and row["day_title"] == "TEST_ Updated"
        finally:
            d = admin.delete(f"{API}/routes/{rid}", timeout=30)
            assert d.status_code in (200, 204)
        assert all(x["id"] != rid for x in admin.get(f"{API}/routes", timeout=30).json())

    def test_delete_unknown_route_404(self, admin):
        r = admin.delete(f"{API}/routes/does-not-exist-xyz", timeout=30)
        assert r.status_code == 404, f"expected 404, got {r.status_code} {r.text[:200]}"

    def test_finance_cannot_create_route(self, finance):
        r = finance.post(f"{API}/routes", json={"from_place": "TEST_F", "to_place": "TEST_G"}, timeout=30)
        assert r.status_code == 403


# ---------------- Occupancy extras costing ----------------
def _deluxe_hotel(admin):
    hotels = admin.get(f"{API}/hotels", timeout=30).json()
    h = next((x for x in hotels if x["name"] == "Hotel Himalayan View"), None)
    assert h, "seeded Hotel Himalayan View missing"
    room = next((r for r in h["rooms"] if r["category"] == "Deluxe"), None)
    assert room, "Deluxe room missing"
    return h, room


class TestOccupancyExtras:
    def test_preview_cost_extras(self, admin):
        h, _ = _deluxe_hotel(admin)
        payload = {
            "adults": 3, "cwb": 1, "cnb": 1, "start_date": "2026-11-10",
            "days": [{"day": 1, "hotel_id": h["id"], "room_category": "Deluxe", "meal_plan": "map"}],
            "pricing": {"margin_pct": 25, "discount": 0, "gst_pct": 5, "gst_enabled": True},
        }
        r = admin.post(f"{API}/itineraries/preview-cost", json=payload, timeout=30)
        assert r.status_code == 200, r.text
        c = r.json()
        assert c["extra_bed_cost"] == 1200
        assert c["cwb_cost"] == 900
        assert c["cnb_cost"] == 400
        assert c["hotel_cost"] == 6700

    def test_breakdown_sums_to_total(self, admin):
        h, _ = _deluxe_hotel(admin)
        body = {
            "title": "TEST_ Round4 Breakdown", "customer_name": "TEST_ Guest",
            "customer_email": "delivered@resend.dev", "destination": "Sikkim/Darjeeling",
            "start_date": "2026-11-10", "adults": 3, "cwb": 1, "cnb": 1, "pax": 5,
            "days": [
                {"day": 1, "title": "Transfer to Gangtok", "description": "<p>d1</p>", "hotel_id": h["id"], "room_category": "Deluxe", "meal_plan": "map"},
                {"day": 2, "title": "Full Day Excursion to Tsomgo Lake & Baba Mandir", "excursion": "Tsomgo Lake & Baba Mandir", "from_place": "Gangtok", "description": "<p>d2</p>", "hotel_id": h["id"], "room_category": "Deluxe", "meal_plan": "map", "activity_cost": 500},
                {"day": 3, "title": "Transfer to Pelling via Ravangla Sightseeing", "from_place": "Gangtok", "to_place": "Pelling", "via": "Ravangla", "description": "<p>d3</p>"},
            ],
            "pricing": {"margin_pct": 25, "discount": 1000, "gst_pct": 5, "gst_enabled": True},
            "terms": {k: f"<p>TEST_ {k}</p>" for k in ("inclusions", "exclusions", "payment_policy", "cancellation_policy", "important_notes")},
        }
        r = admin.post(f"{API}/itineraries", json=body, timeout=30)
        assert r.status_code == 200, r.text
        itin = r.json()
        iid, token = itin["id"], itin["share_token"]
        try:
            share = requests.get(f"{API}/share/{token}", timeout=30)
            assert share.status_code == 200, share.text
            s = share.json()
            rows = s["price_breakdown"]
            assert rows, "price_breakdown empty"
            rows_sum = round(sum(x["amount"] for x in rows), 2)
            assert rows_sum == s["total"], f"breakdown rows sum {rows_sum} != total {s['total']} rows={rows}"
        finally:
            admin.delete(f"{API}/itineraries/{iid}", timeout=30)

    def test_stays_grouping(self, admin):
        h, _ = _deluxe_hotel(admin)
        hotels = admin.get(f"{API}/hotels", timeout=30).json()
        h2 = next((x for x in hotels if x["id"] != h["id"] and x.get("rooms")), None)
        assert h2, "need a second seeded hotel"
        r2cat = h2["rooms"][0]["category"]
        body = {
            "title": "TEST_ Round4 Stays", "customer_name": "TEST_ Guest",
            "customer_email": "delivered@resend.dev", "destination": "Sikkim/Darjeeling",
            "start_date": "2026-11-10", "adults": 2, "pax": 2,
            "days": [
                {"day": 1, "title": "D1", "description": "<p>d</p>", "hotel_id": h["id"], "room_category": "Deluxe", "meal_plan": "map"},
                {"day": 2, "title": "D2", "description": "<p>d</p>", "hotel_id": h["id"], "room_category": "Deluxe", "meal_plan": "map"},
                {"day": 3, "title": "D3", "description": "<p>d</p>", "hotel_id": h2["id"], "room_category": r2cat, "meal_plan": "cp"},
                {"day": 4, "title": "D4", "description": "<p>d</p>"},
            ],
            "pricing": {"margin_pct": 25, "discount": 0, "gst_pct": 5, "gst_enabled": True},
            "terms": {k: f"<p>TEST_ {k}</p>" for k in ("inclusions", "exclusions", "payment_policy", "cancellation_policy", "important_notes")},
        }
        r = admin.post(f"{API}/itineraries", json=body, timeout=30)
        assert r.status_code == 200, r.text
        itin = r.json()
        iid, token = itin["id"], itin["share_token"]
        try:
            s = requests.get(f"{API}/share/{token}", timeout=30).json()
            stays = s["stays"]
            assert len(stays) == 2, stays
            assert stays[0]["nights"] == 2
            assert stays[0]["check_in"] == "2026-11-10"
            assert stays[0]["check_out"] == "2026-11-12"
            assert stays[0]["room_category"] == "Deluxe"
            assert "MAP" in stays[0]["meal_plan"]  # resolved label e.g. "Breakfast + Dinner (MAP)"
            assert stays[1]["nights"] == 1
            assert stays[1]["check_in"] == "2026-11-12"
            assert stays[1]["check_out"] == "2026-11-13"
            # day-level via/excursion echoed for badges
            days = s["days"]
            assert days[0]["date"] if "date" in days[0] else True
        finally:
            admin.delete(f"{API}/itineraries/{iid}", timeout=30)


# ---------------- Share payload day fields for badges ----------------
class TestShareDayFields:
    def test_via_excursion_present_in_share_days(self, admin):
        body = {
            "title": "TEST_ Round4 Badges", "customer_name": "TEST_ Guest",
            "customer_email": "delivered@resend.dev", "destination": "Sikkim/Darjeeling",
            "start_date": "2026-11-10", "adults": 2, "pax": 2,
            "days": [
                {"day": 1, "title": "Transfer to Pelling via Ravangla Sightseeing", "from_place": "Gangtok", "to_place": "Pelling", "via": "Ravangla", "route_type": "via", "description": "<p>d</p>"},
                {"day": 2, "title": "Full Day Excursion to Tsomgo Lake & Baba Mandir", "from_place": "Gangtok", "excursion": "Tsomgo Lake & Baba Mandir", "route_type": "excursion", "description": "<p>d</p>"},
            ],
            "pricing": {"margin_pct": 25, "discount": 0, "gst_pct": 5, "gst_enabled": True},
            "terms": {k: f"<p>TEST_ {k}</p>" for k in ("inclusions", "exclusions", "payment_policy", "cancellation_policy", "important_notes")},
        }
        r = admin.post(f"{API}/itineraries", json=body, timeout=30)
        assert r.status_code == 200, r.text
        itin = r.json()
        iid, token = itin["id"], itin["share_token"]
        try:
            s = requests.get(f"{API}/share/{token}", timeout=30).json()
            d1, d2 = s["days"][0], s["days"][1]
            assert d1.get("via") == "Ravangla", f"via missing in share day: {d1}"
            assert d2.get("excursion") == "Tsomgo Lake & Baba Mandir", f"excursion missing: {d2}"
        finally:
            admin.delete(f"{API}/itineraries/{iid}", timeout=30)
